Added basic navigation information
MisterIXI/prom23 pull request #5
Opened 2023-07-04 18:12 UTC by MisterIXI

2023-07-18 13:30 UTC, v0rl0ck requested changes

2023-07-18 13:30 UTC, v0rl0ck commented on Navigation.md
> +roslaunch turtlebot3_navigation turtlebot3_navigation.launch map_file:=/home/yannik/map_new.yaml```
Move the ``` to the next line, formatting is broken

2023-07-18 13:30 UTC, v0rl0ck commented on Navigation.md
> +rospack find turtlebot3_navigation```
Move the ``` to the next line, formatting is broken

2023-07-18 13:30 UTC, v0rl0ck commented on Navigation.md
> +/opt/ros/melodic/share/turtlebot3_navigation/param
Add quotes to mark the path in the markdown

2023-07-27 15:36 UTC, MisterIXI commented on Navigation.md
> +rospack find turtlebot3_navigation```
Done

2023-07-27 15:36 UTC, MisterIXI commented on Navigation.md
> +/opt/ros/melodic/share/turtlebot3_navigation/param
Done

2023-07-27 15:37 UTC, MisterIXI commented on Navigation.md
> +roslaunch turtlebot3_navigation turtlebot3_navigation.launch map_file:=/home/yannik/map_new.yaml```
Done

2023-07-27 15:38 UTC, v0rl0ck approved these changes
Looks good now :D

2023-07-27 15:38 UTC, merged